// This file is auto-generated by @hey-api/openapi-ts

export type Author = {
    name: string;
    email: string;
    link: string;
    userGroups: Array<UserGroup>;
};

export type DocumentType = {
    type: string;
    name: string;
    count: number;
};

export type DocumentsWithAuthors = {
    documents: Array<UmbracoDocument>;
    authors: Array<Author>;
};

export type UmbracoDocument = {
    status: number;
    name: string;
    link: string;
    type: string;
    typeName: string;
    authorKey: string;
    updateDate: string;
};

export type UserGroup = {
    name: string;
    key: string;
};

export type GetUmbracoManagementApiV1ContentInsightsGetAllDocumentsWithAuthorsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/content-insights/get-all-documents-with-authors';
};

export type GetUmbracoManagementApiV1ContentInsightsGetAllDocumentsWithAuthorsErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetUmbracoManagementApiV1ContentInsightsGetAllDocumentsWithAuthorsResponses = {
    /**
     * OK
     */
    200: DocumentsWithAuthors;
};

export type GetUmbracoManagementApiV1ContentInsightsGetAllDocumentsWithAuthorsResponse = GetUmbracoManagementApiV1ContentInsightsGetAllDocumentsWithAuthorsResponses[keyof GetUmbracoManagementApiV1ContentInsightsGetAllDocumentsWithAuthorsResponses];

export type GetUmbracoManagementApiV1ContentInsightsGetDocumentTypesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/management/api/v1/content-insights/get-document-types';
};

export type GetUmbracoManagementApiV1ContentInsightsGetDocumentTypesErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
    /**
     * The authenticated user does not have access to this resource
     */
    403: unknown;
};

export type GetUmbracoManagementApiV1ContentInsightsGetDocumentTypesResponses = {
    /**
     * OK
     */
    200: Array<DocumentType>;
};

export type GetUmbracoManagementApiV1ContentInsightsGetDocumentTypesResponse = GetUmbracoManagementApiV1ContentInsightsGetDocumentTypesResponses[keyof GetUmbracoManagementApiV1ContentInsightsGetDocumentTypesResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};
