name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'
env:
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  
jobs:
  build-and-publish-nuget-package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore src/SBD.ContentInsights/SBD.ContentInsights.csproj

      - name: Build project
        run: dotnet build src/SBD.ContentInsights/SBD.ContentInsights.csproj --configuration Release --no-restore

      - name: 'Get Version'
        id: version
        uses: battila7/get-version-action@v2
        
      - name: Pack NuGet package
        run: dotnet pack src/SBD.ContentInsights/SBD.ContentInsights.csproj --configuration Release --no-build --include-symbols -p:PackageVersion=${{ steps.version.outputs.version-without-v }} -o ${{ env.PACKAGE_OUTPUT_DIRECTORY }}
      
      - name: Push NuGet package
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
